### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by hangar2apps** [hangar2apps/Unfazedkikz#1]
- [ ] have Featured Kicks section on upload page
- [ ] have shoe of the week section on upload page
- [x] upload shoes through upload page
- [x] get shoes displaying on site
- [ ] get all shoe stores for shoe brand dropdown list
- [ ] get all shoe line for shoe line dropdown list
- [ ] add Shoe of the Week section
